import faker from 'faker';

import { encodeUnicode } from '../utils';

export const getFeatures = (type = 0, pageSize = 10) =>
  new Array(pageSize).fill().map(() =>
    //eslint-disable-line
    ({
      _id: faker.random.uuid(),
      type,
      markName: faker.internet.userName(),
      name: faker.internet.userName(),
      model: 2,
    }));

export const imageFeatures = {
  featureDetails: [
    {
      age: 'youth',
      area: [412, 162, 50, 54],
      baby: 'no baby',
      bag: 'carry nothing in hand',
      barrow: 'no barrow',
      bottomcolor: 'black',
      bottomtype: 'full length pants',
      features: {
        age: 'age',
        baby: 'baby',
        bag: 'bag',
        barrow: 'barrow',
        bottomcolor: 'bottomcolor',
        bottomtype: 'bottomtype',
        glasses: 'glasses',
        hair: 'hair',
        hat: 'hat',
        knapsack: 'knapsack',
        mask: 'mask',
        orientation: 'orientation',
        sex: 'sex',
        trolleycase: 'trolleycase',
        umbrella: 'umbrella',
        uppercolor: 'uppercolor',
        uppertexture: 'uppertexture',
        uppertype: 'uppertype',
      },
      glasses: 'no glasses',
      hair: 'covered',
      hat: 'no hat or helmet',
      knapsack: 'no knapsack',
      mask: 'no mask',
      orientation: 'right',
      sex: 'female',
      targetType: 'person',
      trolleycase: 'no trolleycase',
      type: 'motorbike',
      umbrella: 'no umbrella',
      uppercolor: 'red',
      uppertexture: 'pure color',
      uppertype: 'long sleeve',
    },
    {
      age: 'teenager',
      area: [452, 82, 9, 22],
      baby: 'no baby',
      bag: 'carry nothing in hand',
      barrow: 'have barrow',
      bottomcolor: 'black',
      bottomtype: 'full length pants',
      features: {
        age: 'age',
        baby: 'baby',
        bag: 'bag',
        barrow: 'barrow',
        bottomcolor: 'bottomcolor',
        bottomtype: 'bottomtype',
        glasses: 'glasses',
        hair: 'hair',
        hat: 'hat',
        knapsack: 'knapsack',
        mask: 'mask',
        orientation: 'orientation',
        sex: 'sex',
        shoulderbag: 'shoulderbag',
        trolleycase: 'trolleycase',
        umbrella: 'umbrella',
        uppercolor: 'uppercolor',
        uppertexture: 'uppertexture',
        uppertype: 'uppertype',
      },
      glasses: 'no glasses',
      hair: 'covered',
      hat: 'no hat or helmet',
      knapsack: 'no knapsack',
      mask: 'no mask',
      orientation: 'back',
      sex: 'female',
      shoulderbag: 'non-shoulder bag',
      targetType: 'person',
      trolleycase: 'have trolleycas',
      type: 'person',
      umbrella: 'holding an umbrella',
      uppercolor: 'black',
      uppertexture: 'pure color',
      uppertype: 'long sleeve',
    },
  ],
  ratio: '693x410',
};
